//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class StoreCurrencyPack
{
	public string name;
	public string description;
	public string itemID;
	public string productID;
	public string cost;
	public int size;
	public string type;
}